export const Config = {
  MYSQL_ADMIN1_USERNAME: process.env.MYSQL_ADMIN1_USERNAME || "",
  MYSQL_ADMIN1_PASSWORD: process.env.MYSQL_ADMIN1_PASSWORD || "",
  MYSQL_ADMIN2_USERNAME: process.env.MYSQL_ADMIN2_USERNAME || "",
  MYSQL_ADMIN2_PASSWORD: process.env.MYSQL_ADMIN2_PASSWORD || "",
};
